version: '3.8'

services:
  postgres:
    image: postgres
    env_file:
      - ./.dev/envs/postgres.env
    volumes:
      - /home/mclement/projects/emy-room-booking-backend/.dev/db:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
